const data = {
  products: [
    {
      name: 'Camiseta Nike Slim',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 120,
      brand: 'Nike',
      raiting: 4.5,
      numReviews: 10,
      description: 'Camiseta de gran calidad para hacer deporte',
    },
    {
      name: 'Camiseta Adidas Slim',
      slug: 'adidas-slim-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      raiting: 4.0,
      numReviews: 10,
      description: 'Camiseta de gran calidad para hacer deporte',
    },
    {
      name: 'Pantalón Nike Fit',
      slug: 'nike-fit-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      raiting: 4.5,
      numReviews: 14,
      description: 'Pantalón de gran calidad para hacer deporte',
    },
    {
      name: 'Pantalón Adidas fit',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Adidas',
      raiting: 4.5,
      numReviews: 10,
      description: 'Pantalón de gran calidad para hacer deporte',
    },
  ],
};

export default data;
